"""Second  migration

Revision ID: 58a6c7621125
Revises: 6bdd8a9ddae8
Create Date: 2025-05-21 09:28:07.945610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a6c7621125'
down_revision: Union[str, None] = '6bdd8a9ddae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_bot', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('trading_bot', sa.Column('pairs', sa.String(), nullable=True))
    op.add_column('trading_bot', sa.Column('base_order_volume', sa.Integer(), nullable=True))
    op.add_column('trading_bot', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('trading_bot', sa.Column('safety_order_volume', sa.Float(), nullable=True))
    op.add_column('trading_bot', sa.Column('martingale_volume_coefficient', sa.Float(), nullable=True))
    op.add_column('trading_bot', sa.Column('martingale_step_coefficient', sa.Float(), nullable=True))
    op.add_column('trading_bot', sa.Column('max_safety_orders', sa.Integer(), nullable=True))
    op.add_column('trading_bot', sa.Column('active_safety_orders_count', sa.Integer(), nullable=True))
    op.add_column('trading_bot', sa.Column('safety_order_step_percentage', sa.Float(), nullable=True))
    op.add_column('trading_bot', sa.Column('take_profit_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_bot', 'take_profit_type')
    op.drop_column('trading_bot', 'safety_order_step_percentage')
    op.drop_column('trading_bot', 'active_safety_orders_count')
    op.drop_column('trading_bot', 'max_safety_orders')
    op.drop_column('trading_bot', 'martingale_step_coefficient')
    op.drop_column('trading_bot', 'martingale_volume_coefficient')
    op.drop_column('trading_bot', 'safety_order_volume')
    op.drop_column('trading_bot', 'take_profit')
    op.drop_column('trading_bot', 'base_order_volume')
    op.drop_column('trading_bot', 'pairs')
    op.drop_column('trading_bot', 'account_id')
    # ### end Alembic commands ###
