"""Initial migration

Revision ID: 6bdd8a9ddae8
Revises: 
Create Date: 2025-05-20 22:46:56.698927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdd8a9ddae8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('base_order_size', sa.Float(), nullable=True),
    sa.Column('safety_order_size', sa.Float(), nullable=True),
    sa.Column('profit_made', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_bot_id'), 'trading_bot', ['id'], unique=False)
    op.create_index(op.f('ix_trading_bot_name'), 'trading_bot', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_bot_name'), table_name='trading_bot')
    op.drop_index(op.f('ix_trading_bot_id'), table_name='trading_bot')
    op.drop_table('trading_bot')
    # ### end Alembic commands ###
